[package]
name = "bb_anathema"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
anathema = { git = "https://github.com/togglebyte/anathema/", branch = "feature/state-naming" }

[workspace]
members = ["storybook"]
